FROM node:8
# Create app directory
WORKDIR /usr/src/app
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

RUN npm install

RUN npm install -g swagger-editor

# Bundle app source
COPY . .
EXPOSE 3000
CMD [ "npm", "start" ]
